--- #YAML:1.0
name:               App-FonBot-Daemon
version:            0.000_2
abstract:           FonBot daemon
author:
    - Marius Gavrilescu <marius@ieval.ro>
license:            AGPL_3
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache2::Authen::Passphrase:  0
    DB_File:              0
    HTTP::Status:         0
    IRC::Utils:           0
    JSON:                 0
    Log::Log4perl:        0
    MIME::Base64:         0
    perl:                 5.014000
    POE:                  0
    POE::Component::IRC:  0
    POE::Component::IRC::Plugin::AutoJoin:  0
    POE::Component::IRC::Plugin::Connector:  0
    POE::Component::IRC::Plugin::NickServID:  0
    POE::Component::Server::HTTP:  0
    POE::Component::SSLify:  0
    Storable:             0
    Text::ParseWords:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
